### ISSUE TITLE
`thread 'main' panicked at library/alloc/src/raw_vec.rs:534:5`

### ISSUE THREAD

**Issue by Amar1729** [MordechaiHadad/bob#175]
```
❯  RUST_BACKTRACE=1 bob list
┌───────────┬─────────────┐
│  Version  │  Status     │
├───────────┼─────────────┤
│  v0.9.0   │  Installed  │
│  nightly  │  Used       │
thread 'main' panicked at library/alloc/src/raw_vec.rs:534:5:
capacity overflow
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: alloc::raw_vec::capacity_overflow
   3: alloc::slice::<impl [T]>::repeat
   4: alloc::str::<impl str>::repeat
   5: bob::cli::start::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::context::runtime::enter_runtime
   8: tokio::runtime::runtime::Runtime::block_on
   9: bob::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

i just ran `bob update nightly` while `nightly` was the active version. Then ran `bob list`, at which point above exception was thrown.

----

On macOS Ventura 13.6 (ARM m1).

```
❯  bob --version
bob-nvim 2.7.0
```

**Comment by MordechaiHadad** [comment]
check #176

**Comment by MordechaiHadad** [comment]
> I'm facing this issue as well. Could we have a release with the fix?

Ye I'll see if the last PR can be tested today or tomorrow and then create a new release.

**Comment by alejandrodnm** [comment]
Thanks @MordechaiHadad 🙇
