### ISSUE TITLE
Cannot install nightly

### ISSUE THREAD

**Issue by skoch13** [MordechaiHadad/bob#188]
First off thank you for this project! `bob` used to install and upgrade `nightly` tag without any issues, but today the command results in the following error:

```
bob install nightly
Mar 25 10:37:11.515 ERROR Error: Please provide an existing neovim version
```

I tried reinstalling bob, but no go.

**Comment by MordechaiHadad** [comment]
I tried on both windows and linux just now, also updated my bob version via `cargo install` to latest and I can't reproduce the issue.

**Comment by jellydn** [comment]
I've got the same issue on Mac OSX.

<img width="1006" alt="image" src="https://github.com/MordechaiHadad/bob/assets/870029/eef04597-016f-4aa8-b723-c08aaf77e483">

The workaround is using commit hash.

```sh
❯ bob install ad3568a70167ceb870931650afb7dcaed88640ec
```

**Comment by skoch13** [comment]
@MordechaiHadad sorry for not mentioning it from the start, but I use MacOS, brew installation.

**Comment by MordechaiHadad** [comment]
Hmm I see that neovim recently added arm macos distribution, not sure how it relates to this issue though. but I will add the arm support.

**Comment by skoch13** [comment]
that might seem related, as I'm on arm mac

**Comment by MordechaiHadad** [comment]
So i pushed this PR not sure if it will actually fix it out of the box, but would be epic if you could help test this PR by downloading the arm artifact and trying it, I don't own a mac machine so I can't really test it myself.

**Comment by gibfahn** [comment]
Doesn't seem to resolve the issue unfortunately:

```console
❯ $(brew --prefix)/bin/bob install nightly
Mar 25 13:38:26.144 ERROR Error: Please provide an existing neovim version

❯ git rev-parse @
b7ed90b5fd8385477770060f3589d066dadd9fa8

❯ cargo run --release -- install nightly
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/bob install nightly`
Mar 25 13:38:31.576 ERROR Error: Please provide an existing neovim version
```

**Comment by gibfahn** [comment]
Confirmed that it only affects nightly nvim builds

```console
❯ bob install nightly
bob Mar 25 13:41:21.843 ERROR Error: Please provide an existing neovim version

❯ bob install stable
Mar 25 13:41:23.604  INFO Fetching latest version
Mar 25 13:41:24.054  INFO v0.9.5 is already installed
```

**Comment by skoch13** [comment]
It looks like that is the only thing that needed to be changed at this moment

**Comment by MordechaiHadad** [comment]
> It looks like that is the only thing that needed to be changed at this moment

wait really? thats pretty weird.

**Comment by skoch13** [comment]
Well, I suppose the errors returned by Bob on these occasions could be improved, but that's the only thing

**Comment by MordechaiHadad** [comment]
fixed with #189

**Comment by MordechaiHadad** [comment]
If this issue persists comment and I will reopen

**Comment by skoch13** [comment]
I also opened PR for brew formula update https://github.com/Homebrew/homebrew-core/pull/167119

**Comment by skoch13** [comment]
hm, tests fail on installing exact version https://github.com/Homebrew/homebrew-core/pull/167119/files#diff-327989d259cb52e9492be6246676781536f65b1e2361021edca25f7e07c6c3f1

**Comment by MordechaiHadad** [comment]
> hm, tests fail on installing exact version [Homebrew/homebrew-core#167119 (files)](https://github.com/Homebrew/homebrew-core/pull/167119/files#diff-327989d259cb52e9492be6246676781536f65b1e2361021edca25f7e07c6c3f1)

I would help if I knew anything about homebrew formulaes

**Comment by omar25h** [comment]
Isn't this expected to fail? Previous releases assets still have the name `nvim-macos` while the new changes expect that the zip file name additionally contains the architecture.
It is failing for me and I'm on macOS (x86_64)

**Comment by skoch13** [comment]
As far as I understand here is the test that fails: https://github.com/Homebrew/homebrew-core/blob/e7f172d8b1ed3329ae267df91ba1c8f67202bab9/Formula/b/bob.rb#L37

**Comment by skoch13** [comment]
I guess the issue might be that with the last update bob tries to download v0.9.0 for non-existent architecture

**Comment by MordechaiHadad** [comment]
> Isn't this expected to fail? Previous releases assets still have the name `nvim-macos` while the new changes expect that the zip file name additionally contains the architecture. It is failing for me and I'm on macOS (x86_64)

ye true didnt take it into consideration

**Comment by MordechaiHadad** [comment]
> I guess the issue might be that with the last update bob tries to download [v0.9.0](https://github.com/neovim/neovim/releases/tag/v0.9.0) for non-existent architecture

It is, these new macos files only exist for nightly now.

**Comment by nicklimmm** [comment]
It seems that the change is causing a panic. I am trying to install nightly after running erase.

```
thread 'main' panicked at <erased>/bob-nvim-2.8.2/src/main.rs:85:14:
Failed to spawn child process: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jellydn** [comment]
FYI, I've got same issue with bob-nvim 2.8.2 on Max OSX.

```sh
❯ bob use stable
Mar 26 07:23:41.979  INFO Fetching latest version
Mar 26 07:23:43.886 ERROR Error: Please provide an existing neovim version
❯ bob use nightly
Downloaded version nightly to /Users/huynhdung/.local/share/bob/nightly.tar.gz
  [00:00:00] [██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 8.77MiB/8.77MiB (12.39MiB/s, 0s)
Finished expanding to /Users/huynhdung/.local/share/bob/nightly
  [00:00:00] [█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 1692/1692
Mar 26 07:23:49.813  INFO You can now use nightly!
❯ nvim
thread 'main' panicked at /Users/huynhdung/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bob-nvim-2.8.2/src/main.rs:85:14:
Failed to spawn child process: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by nicklimmm** [comment]
> Looks like you missed the other one:
> 
> https://github.com/MordechaiHadad/bob/blob/8b86468602221c97d5e594d9ebbfbc31310e1e69/src/helpers/mod.rs#L23
> 
> ([#189 (comment)](https://github.com/MordechaiHadad/bob/pull/189#discussion_r1537660436) was included but not [#189 (comment)](https://github.com/MordechaiHadad/bob/pull/189#discussion_r1537631086))

This change will only work on nightly releases since stable releases doesn't have separate assets for x86 and arm.

I suppose we have to pass a flag to the function to handle such cases.

**Comment by omar25h** [comment]
> FYI, I've got same issue with bob-nvim 2.8.2 on Max OSX.
> 
> ```shell
> ❯ bob use stable
> Mar 26 07:23:41.979  INFO Fetching latest version
> Mar 26 07:23:43.886 ERROR Error: Please provide an existing neovim version
> ❯ bob use nightly
> Downloaded version nightly to /Users/huynhdung/.local/share/bob/nightly.tar.gz
>   [00:00:00] [██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 8.77MiB/8.77MiB (12.39MiB/s, 0s)
> Finished expanding to /Users/huynhdung/.local/share/bob/nightly
>   [00:00:00] [█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 1692/1692
> Mar 26 07:23:49.813  INFO You can now use nightly!
> ❯ nvim
> thread 'main' panicked at /Users/huynhdung/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bob-nvim-2.8.2/src/main.rs:85:14:
> Failed to spawn child process: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

a quick workaround would be to `cp -r ~/.local/share/bob/nightly/nvim-macos-x86_84 ~/.local/shrare/bob/nvim-macos` (or nvim-macos-arm64, depending on your current system).

**Comment by MordechaiHadad** [comment]
Latest PR should fix this I hope.

**Comment by jellydn** [comment]
All good now @MordechaiHadad Thanks :)
