### ISSUE TITLE
Not working on Ampere A1 arm archicture

### ISSUE THREAD

**Issue by ocrumbs** [MordechaiHadad/bob#245]
Built from source, since the provided binary on releases page did not work either.

```sh
 RUST_BACKTRACE=1 /home/ubuntu/.local/share/bob/nvim-bin/nvim
thread 'main' panicked at src/main.rs:85:14:
Failed to spawn child process: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: tokio::runtime::park::CachedParkThread::block_on
   4: tokio::runtime::context::runtime::enter_runtime
   5: tokio::runtime::runtime::Runtime::block_on
   6: bob::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

![image](https://github.com/user-attachments/assets/cb28208a-8eaf-4c8b-9639-50fc70bb3ab6)

**Comment by MordechaiHadad** [comment]
Duplicate so I am closing this, but look at #100 #181

**Comment by ocrumbs** [comment]
Thanks for the update :+1:
