### ISSUE TITLE
MacBook M1 Pro install problem

### ISSUE THREAD

**Issue by mrxiaozhuox** [MordechaiHadad/bob#32]
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/modules/expand_archive.rs:12:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/41265098/179779731-e5f29791-f239-46a0-83b1-327bf1444ad1.png">

**Comment by mosheavni** [comment]
I get the same error with amd CPU

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox currently M1 is not supported I am actually surprised you got bob running in the first place...
there's also a #22 which I am meaning to resolve, but since there's no GitHub runner or docker support I can't really test it...

**Comment by MordechaiHadad** [comment]
> I get the same error with amd CPU

Okay now this is weird can you provide what OS you are using?(Unless you are using MacOS I don't really know how apple works regarding their specs)

**Comment by diandian2710** [comment]
I got the same error with intel mac

**Comment by MordechaiHadad** [comment]
This will be a bit harder to debug as I don't own a Mac Machine, so i will need someone to actively test when I open the related PR.

**Comment by mrxiaozhuox** [comment]
> This will be a bit harder to debug as I don't own a Mac Machine, so i will need someone to actively test when I open the related PR.

maybe I can help you.

**Comment by MordechaiHadad** [comment]
@mrxiaozhuox that is good thank you! I will try looking at the code base tomorrow and just see what line of code might have triggered this weird error.

**Comment by MordechaiHadad** [comment]
Would be great if u can test the PR CI builds and give me feedback @mrxiaozhuox

**Comment by MordechaiHadad** [comment]
@diandian2710 @mosheavni can you guys also check the PR builds? it seems like for some odd reason for @mrxiaozhuox it works(even tho I changed practically nothing)

**Comment by MordechaiHadad** [comment]
@mosheavni @diandian2710 @mrxiaozhuox any updates regarding this issue?

**Comment by daiyam** [comment]
Same issue on a mac intel

**Comment by MordechaiHadad** [comment]
@daiyam can you try the macos build from here https://github.com/MordechaiHadad/bob/actions/runs/2903066777
and see if the issue persists?

**Comment by daiyam** [comment]
It's better but I have several issues:
- the link `/Users/user/Library/Application Support/neovim` goes `/Users/user/Library/Application Support/bob/v0.7.2/nvim-osx64` instead of `/Users/user/Library/Application Support/bob/v0.7.2/nvim-macos`
- `nvim` was missing the execute mode
- `nvim` throws me the error `dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin` (surely because I'm using an old version on macos...)
- before the fixes, `bob list` was printing `Error: Neovim is not installed`
- after the fixes, `bob list` is printing `thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/modules/utils.rs:124:38`

**Comment by MordechaiHadad** [comment]
@max397574 do you get the same behavior as @daiyam?

**Comment by max397574** [comment]
I got the same error as mentioned in the original comment in this issue
it was fixed with the pr you told me to test in the duplicate issue of this

**Comment by MordechaiHadad** [comment]
@max397574 is `bob list` working properly?

**Comment by MordechaiHadad** [comment]
weird... @daiyam can you run `bob erase` and see if this persists?

**Comment by cscovino** [comment]
> It's better but I have several issues:
> 
>     * the link `/Users/user/Library/Application Support/neovim` goes `/Users/user/Library/Application Support/bob/v0.7.2/nvim-osx64` instead of `/Users/user/Library/Application Support/bob/v0.7.2/nvim-macos`
> 
>     * `nvim` was missing the execute mode
> 
>     * `nvim` throws me the error `dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin` (surely because I'm using an old version on macos...)
> 
>     * before the fixes, `bob list` was printing `Error: Neovim is not installed`
> 
>     * after the fixes, `bob list` is printing `thread 'main' panicked at 'called `Option::unwrap()`on a`None` value', src/modules/utils.rs:124:38`

I have the same issues:
```
ls -l Library/Application\ Support/neovim
lrwxr-xr-x  1 cscovino  staff  65 Oct 14 12:22 Library/Application Support/neovim -> /Users/cscovino/Library/Application Support/bob/v0.8.0/nvim-osx64
bob list
Oct 14 12:33:02.089 ERROR Error: Neovim is not installed
```
what are the steps to fix it?
